apiVersion: v1
kind: Pod
metadata:
  name: ffmpeg
  namespace: shifu-app
spec:
  restartPolicy: Never
  containers:
    - image: edgehub/ffmpeg:nightly
      command: [ "/bin/sh" ]
      args: [ "-c", "ffmpeg -re -stream_loop -1 -i sample1.mp4 -c copy -f rtsp -rtsp_transport tcp rtsp://rtsp-server.shifu-app.svc.cluster.local:8554/mystream" ]
      name: ffmpeg
