apiVersion: v1
kind: Namespace
metadata:
  name: shifu-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rtsp-record-sa
  namespace: shifu-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rtsp-record-secret-view-clusterrolebinding
  namespace: shifu-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-view
subjects:
  - kind: ServiceAccount
    name: rtsp-record-sa
    namespace: shifu-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-view
  namespace: shifu-app
rules:
  - apiGroups:
      - "" # "" indicates the core API group
    resources:
      - "secrets"
    verbs: [ "get", "list", "watch" ]
